### ISSUE TITLE
Feature Request: Use static password instead of random password

### ISSUE THREAD

**Issue by BeatLink** [saierd/docker-etesync#6]
Using a static password would allow the password to be documented in the readme, so that the docker container can be started without the user needing to read its output for the randomly generated password. The user can then change the default password on login

**Comment by BeatLink** [comment]
This can be done through an environment variable to let the user decide

**Comment by BeatLink** [comment]
Any updates on this?

**Comment by saierd** [comment]
I guess, I can add a possibility to specify a fixed password with an environment variable. I will do that when I work on this project the next time.

I don't like using the same password for all instances, since from my experience nobody will change that and people will expose their instance with the default password on the internet.

What exactly is your use case and why can't you read the password from the container output?

**Comment by BeatLink** [comment]
I have a personal server that runs through a virtual LAN and its not internet routable, so security is not so much of a concern to me. When I'm installing the server I do it unattended through scripts and such. Needing to view the docker installation logs to get the random password breaks that automation, and its redundant in my case since the admin password is one of the first things i change

**Comment by BeatLink** [comment]
you could set the new user to admin and the password to password or changeme
